# Generated by Django 4.0.6 on 2022-08-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('etiqueta', models.CharField(max_length=150)),
                ('cc_botella', models.IntegerField(default=750)),
                ('precio_botella', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Copas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=150)),
                ('etiqueta', models.CharField(max_length=150)),
                ('cosecha', models.DateField(blank=True, null=True)),
                ('cc_botella', models.IntegerField(default=750)),
                ('precio_botella', models.FloatField()),
                ('precio_caja', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
