# Generated by Django 4.0.6 on 2022-08-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDC_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinos',
            name='cosecha',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
