# Generated by Django 4.0.6 on 2022-08-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDC_App', '0002_alter_vinos_cosecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('contenido', models.CharField(max_length=2000)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
